### PR TITLE
move item in scope of loader, remove all utility mcData vars with 1

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by Karang — APPROVED** [review]

**Comment by extremeheat** [comment]
I believe the reason behind not putting it in the loader was to not recreate the function every time a new item gets created. Looks like there’s variables in the current scope that get passed into the function so it’s likely the function gets recreated every time now. Not sure how significant impact would be here, but it may be ignorable.

**Comment by u9g** [comment]
> I believe the reason behind not putting it in the loader was to not recreate the function every time a new item gets created. Looks like there’s variables in the current scope that get passed into the function so it’s likely the function gets recreated every time now. Not sure how significant impact would be here, but it may be ignorable.

The problem with not having mcData in scope is that then you can't test many versions since the version changes every time you call the loader.

**Comment by extremeheat** [comment]
Ok, there’s ways to fix that, I don’t think changing Item versions is a common use case. But look at how prismarine-block handles this

**Comment by u9g** [comment]
> Ok, there’s ways to fix that, I don’t think changing Item versions is a common use case. But look at how prismarine-block handles this

if you would like to you can implement that here too, but we will need `mcData.enchantments` too in the future, so include that please.

**Comment by extremeheat** [comment]
I did a benchmark to fill about 4 chests with items:

```js
var g = {}
function loader(salt) {
	g.salt = salt
	return MyClass
}

class MyClass {
	addTwoNumbers(a, b) {
		return a + b + g.salt
	}
}

for(var i = 0; i < 256; i++) {
	var clas = loader(20)
	new clas().addTwoNumbers(40,40)	
}
```

```js
function loader(salt) {
	return (class MyClass {
		addTwoNumbers(a, b) {
			return a + b + salt
	}})
}

for(var i = 0; i < 256; i++) {
	var clas = loader(20)
	new clas().addTwoNumbers(40,40)	
}
```
like above
```js
Static x 40,590 ops/sec ±5.06% (77 runs sampled)
Runtime x 479 ops/sec ±4.83% (67 runs sampled)
Fastest is Static
```

with static classes:
```js
Static x 140,122 ops/sec ±3.89% (77 runs sampled)
Runtime x 1,356 ops/sec ±6.50% (61 runs sampled)
Fastest is Static
```

So it's 98% slower instantiating a new object

**Comment by u9g** [comment]
> I did a benchmark to fill about 4 chests with items:
> 
> ```js
> var g = {}
> function loader(salt) {
> 	g.salt = salt
> 	return MyClass
> }
> 
> class MyClass {
> 	addTwoNumbers(a, b) {
> 		return a + b + g.salt
> 	}
> }
> 
> for(var i = 0; i < 256; i++) {
> 	var clas = loader(20)
> 	new clas().addTwoNumbers(40,40)	
> }
> ```
> 
> ```js
> function loader(salt) {
> 	return (class MyClass {
> 		addTwoNumbers(a, b) {
> 			return a + b + salt
> 	}})
> }
> 
> for(var i = 0; i < 256; i++) {
> 	var clas = loader(20)
> 	new clas().addTwoNumbers(40,40)	
> }
> ```
> 
> like above
> 
> ```js
> Static x 40,590 ops/sec ±5.06% (77 runs sampled)
> Runtime x 479 ops/sec ±4.83% (67 runs sampled)
> Fastest is Static
> ```
> 
> with static classes:
> 
> ```js
> Static x 140,122 ops/sec ±3.89% (77 runs sampled)
> Runtime x 1,356 ops/sec ±6.50% (61 runs sampled)
> Fastest is Static
> ```
> 
> So it's 98% slower instantiating a new object
if you feel like its needed, you can implement that here too, but we will need `mcData.enchantments` too in the future, so I'm not sure how we can pass that in

**Comment by extremeheat** [comment]
All you have to do is return a reference to the class with a non-static method like above

```js

class A {
  constructor(a, b) { this.a = a; this.b = b; }
  static addStatic(a, b) { return a + b }
  add() { return this.a + this.b }
}

var a = new A(4,4)
a.add() => 8
A.add(4,4) => 8
```

**Comment by u9g** [comment]
> All you have to do is return a reference to the class with a non-static method like above. Users can be responsible for instantiating that class, or not, to use it as static.
> 
> ```js
> class A {
>   constructor(a, b) { this.a = a; this.b = b; }
>   static addStatic(a, b) { return a + b }
>   add() { return this.a + this.b }
> }
> 
> var a = new A(4,4)
> a.add() => 8
> A.add(4,4) => 8
> ```

standard has problems with the static keyword.

**Comment by extremeheat** [comment]
No, that's only for static and class variables (a ES7 feature), static functions (ES6) should work fine. 
standardjs doesn't track support newer node features, so things from newer versions do break. See https://github.com/standard/standard/issues/1165

**Pull request merged**
