### PR TITLE
Add checks for enchantment name retrieval

### PR DESCRIPTION
**Pull request by firejoust**
Fixes [this issue](https://github.com/PrismarineJS/prismarine-item/issues/52). Sorry for duplicate PR, I couldn't re-open the last one after rebasing

### CODE REVIEW

**Comment by u9g** [comment]
why should this not throw an error? this function is for showing what the enchants has in a standardized format. if the enchants can’t be shown in a standardized format, then it should error?

**Comment by firejoust** [comment]
I see what you mean, but if a name doesn't exist for an enchant it shouldn't terminate the program; Minecraft handles this by not displaying an enchantment name at all (instead of crashing the game), so it would be better if prismarine-item could behave in a similar way, returning null for enchantments that don't have a mapped name. This way, it's more obvious that an enchantment isn't standard and doesn't impose unnecessary consequence to the developer attempting to retrieve enchantments from an item

**Comment by u9g** [comment]
> I see what you mean, but if a name doesn't exist for an enchant it shouldn't terminate the program; Minecraft handles this by not displaying an enchantment name at all (instead of crashing the game), so it would be better if prismarine-item could behave in a similar way, returning null for enchantments that don't have a mapped name. This way, it's more obvious that an enchantment isn't standard and doesn't impose unnecessary consequence to the developer attempting to retrieve enchantments from an item

Okay, so wouldn’t it make sense to return an empty array and maybe add a .hasEnchantGlint() that returns if there is any enchantment on the item? Obviously not a perfect solution, an alternative solution would be to add a way to serialize these invalid enchantments to a normalizedenchant.

**Comment by firejoust** [comment]
Well there's nothing wrong with how enchantments are currently handled during serialization, the problem lies within assuming a single data type (strings only for 1.13+) and IDs [which don't have a name mapped in minecraft-data](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.8/enchantments.json) (1.12.2 and under). This PR prevents that from breaking execution and assigns a null pointer for IDs that cannot be normalized into an enchantment name (due to the enchantments being invalid)

**Comment by rom1504** [comment]
not ideal but better than before

**Pull request merged**
