### PR TITLE
Add `maxDurability` field, fix handling item sent by server with new `sentByServer` arg

### PR DESCRIPTION
**Pull request by extremeheat**

### CODE REVIEW

**Comment by frej4189** [comment]
This will still cause issues in mineflayer when using anvil on items with full durability in 1.13/1.14 due to https://github.com/PrismarineJS/prismarine-item/blob/6ce147eca7672740fde133d3d92a81a6ff9148f6/lib/anvil.js#L47

**Comment by extremeheat** [comment]
OK, so I guess in vanilla it only updates the item damage if the anvil changed the item's durability? Seems so per my comment in #105. In which case simply not updating the durability if it didn't change seems like the more correct solution.

**Comment by frej4189** [comment]
Upon further inspection the combine function in anvil.js seems to have a lot of flaws that will need to be addressed. So I think it makes sense to merge this PR as-is and then address anvil issues in another PR

**Comment by rom1504** [comment]
@extremeheat can you open the corresponding PR in mineflayer so we make sure it works ?

**Comment by frej4189** [comment]
> @extremeheat can you open the corresponding PR in mineflayer so we make sure it works ?

Updated my test PR to depend on this PR instead of #105

**Pull request merged**
