### PR TITLE
Release 1.10.1

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
please fix tests

**Comment by extremeheat** [comment]
Can you fix this (to avoid a merge conflict later on)? should just be a matter of fixing the test incorrect stack amount in the tests

**Comment by u9g** [comment]
> Can you fix this (to avoid a merge conflict later on)? should just be a matter of fixing the test incorrect stack amount in the tests

fixed that, but I think there's something more

**Comment by rom1504** [comment]
ci still failing, do you know what's up @u9g ?

**Comment by u9g** [comment]
fixed it, was a problem upstream

**Pull request merged**
