### PR TITLE
now p-item uses registry instead of mcData (a step towards #2450)

### PR DESCRIPTION
**Pull request by Epirito**
a contribution towards https://github.com/PrismarineJS/mineflayer/issues/2450

### CODE REVIEW

**Comment by rom1504** [comment]
CI failing

**Comment by rom1504** [comment]
Thanks

**Comment by rom1504** [comment]
Doing the same for pentity would be appreciated

**Comment by Epirito** [comment]
Done!

**Comment by rom1504** [comment]
Nice

Last step on this migration is https://github.com/PrismarineJS/mineflayer/issues/2450#issuecomment-1274809390

**Pull request merged**
